### ISSUE TITLE
new items in hasMany relationships aren't cleaned up

### ISSUE THREAD

**Issue by bgentry** [dockyard/ember-data-route#12]
I'm playing around with an Ember app for managing financial portfolios. Each Portfolio model has many Allocations. Disclaimer: I'm extremely new to Ember, so forgive me if any of this makes no sense or if I'm doing things wrong :)

Here are the relevant models:

```js
// in app/models/portfolio.js
export default DS.Model.extend({
  name: DS.attr('string'),
  allocations: DS.hasMany('allocations')
});
```

```js
// in app/models/allocation.js
export default DS.Model.extend({
  assetClass: DS.belongsTo('asset_class', { async: true }),
  portfolio: DS.belongsTo('portfolio'),
  weight: DS.attr('number')
});
```

I have a route and controller for creating a new Portfolio that requires you to define all of its allocations upfront. The controller adds new Allocations to the unsaved Portfolio using `store.createRecord()` and `addObject()`. Here's a sample from that route and controller:

```js
// in app/controllers/portfolio/new.js
export default Ember.ObjectController.extend({
  actions: {
    addAllocation: function() {
      var portfolio = this.get('model');
      var allocation = this.store.createRecord('allocation', {portfolio: portfolio});
      portfolio.get('allocations').addObject(allocation);
    },
    create: function(params) {
      console.log("CREATE PARAMS: ", params);
      var newPortfolio = this.get('model');
      var self = this;
      newPortfolio.save().then(function() {
        self.transitionToRoute('portfolio', newPortfolio);
      });
    }
  }
});
```

```js
// in app/routes/portfolios/new.js
import Ember from 'ember';
import DataRoute from 'ember-data-route/mixins/data-route';

export default Ember.Route.extend(DataRoute, {
  model: function(params) {
    return this.store.createRecord('portfolio', params);
  },
});
```

This package, ember-data-route, is working well for rolling back the unsaved Portfolio when the user changes pages before saving it. However, the unsaved Allocations are not rolled back. This is further complicated by the fact that I'm using embedded relationships to create the Allocations along with the Portfolio in a single HTTP `POST`. As such, when I save the Portfolio & Allocations, I'm directed to the Portfolio page which shows both the previously unsaved Allocations, and the ones that were returned embedded in the HTTP `POST` response.

To work around this, I had to add the following to my Route:

```js
  resetController: function() {
    this._super();

    var model = this.get('controller.model');
    model.eachRelationship(function(name, descriptor) {
      if(descriptor.kind === "hasMany") {
        var items = model.get(name);
        items.forEach(function(item) {
          if(!item.get('isDeleted')) {
            if (item.get('isNew')) {
              item.deleteRecord();
            } else {
              item.rollback();
            }
          }
        });
      }
    });
  }
```

Which will also roll back any unsaved children and remove them from the store. This appears to clear up unsaved records that are left around from either scenario (leaving the page, and successfully saving the Portfolio and Allocations together). The fact that it cleans up after the unsaved embedded records may just be a coincidence, though, since I happen to be doing a `transitionToRoute` after saving it.

It's entirely possible that this is such an unusual situation that I might be the only one who will ever encounter it. It may even be an undesired behavior for most people who use this library.

Regardless, I thought I'd post about it here in case it seems like a scenario that you'd like to support out-of-the-box. I'd be happy to help turn it into a PR if you think it's useful enough and provide me some guidance on how it should work.

Thanks!

**Comment by bcardarella** [comment]
This sounds like an Ember Data problem. @igorT shouldn't the parent's `rollback()` also propagate to its children?

**Comment by igorT** [comment]
@bcardarella they don't currently, thats a super hard problem, and the last major blocker before 1.0

**Comment by bgentry** [comment]
ah, so my "solution" shouldn't be necessary at all, at least not by the time ember-data 1.0 is shipped.

**Comment by knownasilya** [comment]
A semi related issue is the parent's `isDirty` being `true` because of the relationship. @bcardarella would you consider doing a `Ember.default.keys(resolved.theme.changedAttributes())` check to display the confirmation modal? At least in the mean time before 1.0 ships (might handle dirtying differently).

**Comment by bcardarella** [comment]
Closing in favor of this being fixed upstream
