### ISSUE TITLE
model.rollback() deprecated

### ISSUE THREAD

**Issue by sdn90** [dockyard/ember-data-route#18]
http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html#toc_code-store-push-code-changes

`model.rollback()` is renamed to `model.rollbackAttributes()`

**Comment by bcardarella** [comment]
Thank you for the heads up. Could you submit a PR for the fix? Thanks!

On Saturday, July 18, 2015, Steven Nguyen <notifications@github.com> wrote:

>
> http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html#toc_code-store-push-code-changes
>
> model.rollback() is renamed to model.rollbackAttributes()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dockyard/ember-data-route/issues/18>.
>


-- 

----------------------
Brian Cardarella
CEO of DockYard
Visit us: http://dockyard.com
Call us: (855) DOCK-YRD
Follow me on Twitter: http://twitter.com/bcardarella
Follow us on Twitter: http://twitter.com/DockYard

**Comment by sdn90** [comment]
I didn't submit a PR because I wasn't sure if you guys wanted to have it backwards compatible with older Ember versions or just completely drop `model.rollback()`.

`model.rollback()` is not completely removed from Ember 1.13. It just sends a warning about it being deprecated.

**Comment by bcardarella** [comment]
We don't. If people want compatibility with an older version they can use
an older version of this addon

On Saturday, July 18, 2015, Steven Nguyen <notifications@github.com> wrote:

> I didn't submit a PR because I wasn't sure if you guys wanted to have it
> backwards compatible with older Ember versions or just completely drop
> model.rollback().
>
> model.rollback() is not completely removed from Ember 1.13. It just sends
> a warning about it being deprecated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dockyard/ember-data-route/issues/18#issuecomment-122617119>
> .
>


-- 

----------------------
Brian Cardarella
CEO of DockYard
Visit us: http://dockyard.com
Call us: (855) DOCK-YRD
Follow me on Twitter: http://twitter.com/bcardarella
Follow us on Twitter: http://twitter.com/DockYard

**Comment by miguelcobain** [comment]
Similarly, I think that `isDirty` was replaced by [`hasDirtyAttributes`](http://emberjs.com/api/data/classes/DS.Model.html#property_hasDirtyAttributes). Am I right?

**Comment by bcardarella** [comment]
Closed with #21
